# Generated by Django 4.2.3 on 2023-07-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='createt_at',
        ),
    ]
