# Generated by Django 4.2.3 on 2023-07-13 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_created_at_message_createt_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createt_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
